### PR TITLE
Support Bearer authentication using env var `JWT`

### PR DESCRIPTION
**Pull request by dancek**
Hi!

We have JWT authentication in an application and I wanted to use drawbridge with it. Here's an implementation that gets the token from env var `JWT`. It works, but I'll concede that this may not be the most elegant way to do it. I'm open to suggestions.

### CODE REVIEW

**Comment by dancek** [comment]
Looks to me like Travis failed before even running tests.

**Comment by bbatsov** [comment]
Hmm, I thought we had already moved this project over to CircleCI, but I guess we forgot to do this. 

I'm not a big fan of using env variables and I'd suggest leveraging nREPL's config file instead.

**Comment by dancek** [comment]
That's a much better idea. I added full support for any custom HTTP headers because why not. What do you think?

**Comment by dancek** [comment]
@bbatsov how do you feel about this?

**Comment by bbatsov** [comment]
Looks good to me. Thanks!

**Pull request merged**
